"""Risk factors of a EUR trading book and a synthetic daily market history.

The history is generated by a known data-generating process: GARCH(1,1)
volatilities, Student-t innovations and two crisis regimes with higher
volatility and higher correlation. Because the true dynamics are known, the
backtests show which VaR models capture volatility clustering and which do
not, without depending on a market data vendor.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
from scipy.special import expit


@dataclass(frozen=True)
class RiskFactor:
    name: str
    kind: str          # equity | fx | rate | spread | vol
    asset_class: str   # FRTB risk class used for IMCC aggregation
    liquidity_horizon: int
    daily_vol: float   # unconditional vol of the daily change (normal regime)
    level: float       # today's level (spot, rate, spread or implied vol)

    @property
    def is_log(self) -> bool:
        """Equity and FX shocks are log-returns, others absolute changes."""
        return self.kind in ("equity", "fx")


FACTORS: tuple[RiskFactor, ...] = (
    RiskFactor("EQ_EUROPE", "equity", "EQ", 10, 0.0110, 100.0),
    RiskFactor("EQ_US", "equity", "EQ", 10, 0.0105, 100.0),
    RiskFactor("EQ_JAPAN", "equity", "EQ", 10, 0.0120, 100.0),
    RiskFactor("EQ_EM", "equity", "EQ", 20, 0.0125, 100.0),
    RiskFactor("EQ_EU_BANKS", "equity", "EQ", 10, 0.0165, 100.0),
    RiskFactor("FX_EURUSD", "fx", "FX", 10, 0.0055, 1.08),
    RiskFactor("FX_EURGBP", "fx", "FX", 10, 0.0045, 0.85),
    RiskFactor("FX_EURJPY", "fx", "FX", 10, 0.0070, 160.0),
    RiskFactor("IR_EUR_2Y", "rate", "IR", 10, 0.00045, 0.0220),
    RiskFactor("IR_EUR_5Y", "rate", "IR", 10, 0.00055, 0.0240),
    RiskFactor("IR_EUR_10Y", "rate", "IR", 10, 0.00055, 0.0270),
    RiskFactor("IR_EUR_30Y", "rate", "IR", 10, 0.00050, 0.0290),
    RiskFactor("CS_EUR_IG", "spread", "CS", 20, 0.00012, 0.0110),
    RiskFactor("CS_EUR_HY", "spread", "CS", 40, 0.00055, 0.0380),
    RiskFactor("VOL_EQ_EU", "vol", "EQ", 20, 0.0100, 0.180),
    RiskFactor("VOL_EQ_US", "vol", "EQ", 20, 0.0100, 0.160),
)

NAMES = tuple(f.name for f in FACTORS)


def index(name: str) -> int:
    return NAMES.index(name)


def _nearest_corr(c):
    w, v = np.linalg.eigh((c + c.T) / 2)
    c = (v * np.maximum(w, 1e-4)) @ v.T
    d = np.sqrt(np.diag(c))
    return c / np.outer(d, d)


def base_correlation(crisis: bool = False) -> np.ndarray:
    """Plausible daily correlations; crisis raises equity/credit co-movement."""
    n = len(FACTORS)
    c = np.eye(n)

    def put(a, b, rho):
        i, j = index(a), index(b)
        c[i, j] = c[j, i] = rho

    eq = ["EQ_EUROPE", "EQ_US", "EQ_JAPAN", "EQ_EM", "EQ_EU_BANKS"]
    boost = 0.12 if crisis else 0.0
    pairs = {("EQ_EUROPE", "EQ_US"): 0.65, ("EQ_EUROPE", "EQ_JAPAN"): 0.45,
             ("EQ_EUROPE", "EQ_EM"): 0.60, ("EQ_EUROPE", "EQ_EU_BANKS"): 0.85,
             ("EQ_US", "EQ_JAPAN"): 0.40, ("EQ_US", "EQ_EM"): 0.55,
             ("EQ_US", "EQ_EU_BANKS"): 0.55, ("EQ_JAPAN", "EQ_EM"): 0.50,
             ("EQ_JAPAN", "EQ_EU_BANKS"): 0.40, ("EQ_EM", "EQ_EU_BANKS"): 0.55}
    for (a, b), rho in pairs.items():
        put(a, b, min(rho + boost, 0.95))
    for e in eq:
        put(e, "FX_EURUSD", -0.10)
        put(e, "FX_EURJPY", 0.30)
        put(e, "IR_EUR_10Y", 0.30 - (0.1 if crisis else 0.0))
        put(e, "CS_EUR_IG", -0.45 - boost)
        put(e, "CS_EUR_HY", -0.60 - boost)
        put(e, "VOL_EQ_EU", -0.70 - boost / 2)
        put(e, "VOL_EQ_US", -0.60 - boost / 2)
    put("FX_EURUSD", "FX_EURGBP", 0.35)
    put("FX_EURUSD", "FX_EURJPY", 0.45)
    put("FX_EURGBP", "FX_EURJPY", 0.30)
    put("IR_EUR_2Y", "IR_EUR_5Y", 0.90)
    put("IR_EUR_2Y", "IR_EUR_10Y", 0.78)
    put("IR_EUR_2Y", "IR_EUR_30Y", 0.62)
    put("IR_EUR_5Y", "IR_EUR_10Y", 0.92)
    put("IR_EUR_5Y", "IR_EUR_30Y", 0.78)
    put("IR_EUR_10Y", "IR_EUR_30Y", 0.90)
    for r in ["IR_EUR_2Y", "IR_EUR_5Y", "IR_EUR_10Y", "IR_EUR_30Y"]:
        put(r, "FX_EURUSD", 0.25)
        put(r, "CS_EUR_IG", -0.25)
    put("CS_EUR_IG", "CS_EUR_HY", 0.80 + boost / 2)
    put("CS_EUR_IG", "VOL_EQ_EU", 0.50)
    put("CS_EUR_HY", "VOL_EQ_EU", 0.60)
    put("VOL_EQ_EU", "VOL_EQ_US", 0.85)
    put("VOL_EQ_US", "CS_EUR_HY", 0.55)
    return _nearest_corr(c)


@dataclass
class MarketHistory:
    returns: np.ndarray          # (T, F) daily shocks (log or absolute)
    true_vol: np.ndarray         # (T, F) conditional vol of the DGP
    crisis: np.ndarray           # (T,) bool
    factors: tuple[RiskFactor, ...] = FACTORS

    @property
    def n_days(self) -> int:
        return self.returns.shape[0]


def synthetic_history(n_days: int = 2520, seed: int = 11, nu: float = 5.0,
                      crises=((900, 1060), (1900, 1960)), vol_mult: float = 2.4,
                      alpha: float = 0.07, beta: float = 0.91) -> MarketHistory:
    """Ten years of daily risk-factor changes from a regime GARCH-t model.

    h_t = w + alpha * eps_{t-1}^2 + beta * h_{t-1},  eps_t = sqrt(h_t) m_t z_t
    z_t multivariate Student-t (unit variance) with regime correlation and
    m_t = vol_mult in crisis windows. Crisis 1 is long (sovereign/GFC-like),
    crisis 2 short and violent (pandemic-like).
    """
    rng = np.random.default_rng(seed)
    f = len(FACTORS)
    sig = np.array([x.daily_vol for x in FACTORS])
    l_norm = np.linalg.cholesky(base_correlation(False))
    l_cris = np.linalg.cholesky(base_correlation(True))
    crisis = np.zeros(n_days, dtype=bool)
    for a, b in crises:
        crisis[a:b] = True
    # smooth regime intensity: sharp onset, slower decay after the crisis
    ramp = np.zeros(n_days)
    days = np.arange(n_days)
    for a, b in crises:
        on = expit((days - a - 3) / 2.0)
        off = np.where(days < b, 1.0, np.exp(-np.maximum(days - b, 0) / 25.0))
        ramp = np.maximum(ramp, on * off)
    mult = 1 + (vol_mult - 1) * ramp
    w = sig**2 * (1 - alpha - beta)
    h = sig**2
    z_prev = np.zeros(f)
    out = np.empty((n_days, f))
    vol = np.empty((n_days, f))
    scale_t = np.sqrt((nu - 2) / nu)
    for t in range(n_days):
        h = w + alpha * z_prev**2 + beta * h
        chol = l_cris if crisis[t] else l_norm
        g = chol @ rng.standard_normal(f)
        z = np.sqrt(h) * g * np.sqrt(nu / rng.chisquare(nu)) * scale_t
        out[t] = mult[t] * z
        vol[t] = mult[t] * np.sqrt(h)
        z_prev = z
    return MarketHistory(returns=out, true_vol=vol, crisis=crisis)
